name: Python package

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest